### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by Telis21** [EParisot/ESP32_Network_Toolbox_App#1]
I have my own ESP32 how can I make it work. The scan doesn't work. 

Thanks for your time.

**Comment by EParisot** [comment]
Hi ! The esp32 needs code to communicate with the phone (and, more importantly, needs to be specifically compiled to send special packets), but this code isn't public, and I don't know if I will open source it one day...
I can detail the communication protocol between the esp32 and the device, it is very simple, they share a packet to setup the wifi channel and wifi country to operate on, then the esp32 waits for a request (of type snif or deauth), starts the requested action and send back real time pap file stream so the phone can save it.
The app phone juste receive data, save it and parse it for display plus a little bit of analysis (that can be improved though).

**Comment by anmayraj** [comment]
hi i have esp32 wroom and when i connect esp32 with my android phone via otg adapter then it shows my esp32 in list but it doesn't detect it in usb esp32
![146df59d-7fae-4d29-a597-bc0637a6ae06](https://user-images.githubusercontent.com/68437946/210320595-19e06014-35a2-4375-9ed5-4ca37f313ec5.jpg)

**Comment by EParisot** [comment]
Hi what I see seems ok, it is detected but not usefull if you don't have an already programmed ESP32 from me...

**Comment by anmayraj** [comment]
Ohh! Can you please provide the code, I'm so curious about this app as u think it's the only one in the market which is capable of doing this

**Comment by EParisot** [comment]
Well, I sell them : https://www.tindie.com/products/klhnikov/esp32-network-toolbox/

Keep in mind that most modern devices seems to not be sensitives to deauth attacks anymore...
